logging:
  level:
    com:
      paladin:
        upload:
          mapper: DEBUG

server:
  port: 19011

spring:
  application:
    name: greenery-upload
  cloud:
    nacos:
      server-addr: 172.16.16.120:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    name: greenery_upload
    url: jdbc:mysql://172.16.16.120:3306/greenery_upload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15
  redis:
    host: 172.16.16.120
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
  thymeleaf:
    cache: false


ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000


video:
  # ffmpeg 转视频工具命令地址
  ffmpeg: E:/ffmpeg/bin/ffmpeg.exe
  # 上传文件目录
  upload:
    folder: E:/upload/
  # 转码后视频文件目录
  transcode:
    folder: E:/transcode/

attachment:
  # 附件上传目录
  upload-folder: E:/upload/
  # 附件访问基础地址
  visit-base-url: /static/file/
  # 上传附件最大大小（单位M）
  max-file-size: 10
  # 附件删除后保留时间（单位天）
  delete-expire-day: 10

